[app]
name = "eventbox"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = "8050"

[app.grpc]
host = "127.0.0.1"
port = "18050"


[keyauth]
host = "127.0.0.1"
port = "18050"
client_id = "abc"
client_secret = "abc"




[mongodb]
endpoints = ["127.0.0.1:27017"]
username = "eventbox"
password = "123456"
database = "eventbox"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"