// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: apps/notify/voice/pb/notify.proto

package voice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provider int32

const (
	Provider_TENCENT Provider = 0
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "TENCENT",
	}
	Provider_value = map[string]int32{
		"TENCENT": 0,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_notify_voice_pb_notify_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_apps_notify_voice_pb_notify_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_apps_notify_voice_pb_notify_proto_rawDescGZIP(), []int{0}
}

type NotifyStatus int32

const (
	// 呼叫异常
	NotifyStatus_ABNORMAL NotifyStatus = 0
	// 用户正常接听
	NotifyStatus_ANSWERED NotifyStatus = 1
	// 用户未接听
	NotifyStatus_DENY NotifyStatus = 2
)

// Enum value maps for NotifyStatus.
var (
	NotifyStatus_name = map[int32]string{
		0: "ABNORMAL",
		1: "ANSWERED",
		2: "DENY",
	}
	NotifyStatus_value = map[string]int32{
		"ABNORMAL": 0,
		"ANSWERED": 1,
		"DENY":     2,
	}
)

func (x NotifyStatus) Enum() *NotifyStatus {
	p := new(NotifyStatus)
	*p = x
	return p
}

func (x NotifyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_notify_voice_pb_notify_proto_enumTypes[1].Descriptor()
}

func (NotifyStatus) Type() protoreflect.EnumType {
	return &file_apps_notify_voice_pb_notify_proto_enumTypes[1]
}

func (x NotifyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyStatus.Descriptor instead.
func (NotifyStatus) EnumDescriptor() ([]byte, []int) {
	return file_apps_notify_voice_pb_notify_proto_rawDescGZIP(), []int{1}
}

type RecordSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"total"
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	// @gotags: json:"items"
	Items []*Record `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
}

func (x *RecordSet) Reset() {
	*x = RecordSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_notify_voice_pb_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSet) ProtoMessage() {}

func (x *RecordSet) ProtoReflect() protoreflect.Message {
	mi := &file_apps_notify_voice_pb_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSet.ProtoReflect.Descriptor instead.
func (*RecordSet) Descriptor() ([]byte, []int) {
	return file_apps_notify_voice_pb_notify_proto_rawDescGZIP(), []int{0}
}

func (x *RecordSet) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RecordSet) GetItems() []*Record {
	if x != nil {
		return x.Items
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 标准Id
	// @gotags: json:"id" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"_id"`
	// 触发时间
	// @gotags: json:"trigger_at" bson:"trigger_at"
	TriggerAt int64 `protobuf:"varint,2,opt,name=trigger_at,json=triggerAt,proto3" json:"trigger_at" bson:"trigger_at"`
	// 厂商
	// @gotags: json:"provider" bson:"provider"
	Provider Provider `protobuf:"varint,3,opt,name=provider,proto3,enum=infraboard.eventbox.voice.Provider" json:"provider" bson:"provider"`
	// 被叫手机号码，采用 e.164 标准，格式为+[国家或地区码][用户号码], 例如：+8613711112222，其中前面有一个+号，86为国家码，13711112222为手机号
	// @gotags: json:"called_number" bson:"called_number"
	CalledNumber string `protobuf:"bytes,4,opt,name=called_number,json=calledNumber,proto3" json:"called_number" bson:"called_number"`
	// 号码所属人
	// @gotags: json:"number_owner" bson:"number_owner"
	NumberOwner string `protobuf:"bytes,8,opt,name=number_owner,json=numberOwner,proto3" json:"number_owner" bson:"number_owner"`
	// 要发送的消息
	// @gotags: json:"message" bson:"message"
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message" bson:"message"`
	// 响应
	// @gotags: json:"response" bson:"response"
	Response *Response `protobuf:"bytes,6,opt,name=response,proto3" json:"response" bson:"response"`
	// 回调
	// @gotags: json:"callback" bson:"callback"
	Callback *Callback `protobuf:"bytes,7,opt,name=callback,proto3" json:"callback" bson:"callback"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_notify_voice_pb_notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_apps_notify_voice_pb_notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_apps_notify_voice_pb_notify_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Record) GetTriggerAt() int64 {
	if x != nil {
		return x.TriggerAt
	}
	return 0
}

func (x *Record) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_TENCENT
}

func (x *Record) GetCalledNumber() string {
	if x != nil {
		return x.CalledNumber
	}
	return ""
}

func (x *Record) GetNumberOwner() string {
	if x != nil {
		return x.NumberOwner
	}
	return ""
}

func (x *Record) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Record) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Record) GetCallback() *Callback {
	if x != nil {
		return x.Callback
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否成功
	// @gotags: json:"success" bson:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success" bson:"success"`
	// 错误消息，result 非0时的具体错误信息
	// @gotags: json:"err_msg" bson:"err_msg"
	ErrMsg string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg" bson:"err_msg"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_notify_voice_pb_notify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_apps_notify_voice_pb_notify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_apps_notify_voice_pb_notify_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 厂商
	// @gotags: json:"provider" bson:"provider"
	Provider Provider `protobuf:"varint,1,opt,name=provider,proto3,enum=infraboard.eventbox.voice.Provider" json:"provider" bson:"provider"`
	// 被叫手机号码，采用 e.164 标准，格式为+[国家或地区码][用户号码], 例如：+8613711112222，其中前面有一个+号，86为国家码，13711112222为手机号
	// @gotags: json:"called_numbers" bson:"called_numbers" validate:"required"
	CalledNumbers []string `protobuf:"bytes,2,rep,name=called_numbers,json=calledNumbers,proto3" json:"called_numbers" bson:"called_numbers" validate:"required"`
	// 要发送的消息
	// @gotags: json:"message" bson:"message" validate:"required"
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message" bson:"message" validate:"required"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_notify_voice_pb_notify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_apps_notify_voice_pb_notify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_apps_notify_voice_pb_notify_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_TENCENT
}

func (x *Request) GetCalledNumbers() []string {
	if x != nil {
		return x.CalledNumbers
	}
	return nil
}

func (x *Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Callback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"result" bson:"result"
	Result NotifyStatus `protobuf:"varint,1,opt,name=result,proto3,enum=infraboard.eventbox.voice.NotifyStatus" json:"result" bson:"result"`
	// 用户接听时间
	// @gotags: json:"accept_time" bson:"accept_time"
	AcceptTime int64 `protobuf:"varint,2,opt,name=accept_time,json=acceptTime,proto3" json:"accept_time" bson:"accept_time"`
	// 呼入号码
	// @gotags: json:"call_from" bson:"call_from"
	CallFrom string `protobuf:"bytes,3,opt,name=call_from,json=callFrom,proto3" json:"call_from" bson:"call_from"`
	// 标识本次发送 ID
	// @gotags: json:"callid" bson:"callid" validate:"required"
	CallId string `protobuf:"bytes,4,opt,name=call_id,json=callId,proto3" json:"callid" bson:"callid" validate:"required"`
	// 结束语音通知呼叫时间
	// @gotags: json:"end_calltime" bson:"end_calltime"
	EndCalltime int64 `protobuf:"varint,5,opt,name=end_calltime,json=endCalltime,proto3" json:"end_calltime" bson:"end_calltime"`
	// 计费时长，单位为分钟
	// @gotags: json:"fee" bson:"fee"
	Fee string `protobuf:"bytes,6,opt,name=fee,proto3" json:"fee" bson:"fee"`
	// 手机号码
	// @gotags: json:"mobile" bson:"mobile"
	Mobile string `protobuf:"bytes,7,opt,name=mobile,proto3" json:"mobile" bson:"mobile"`
	// 国家（或地区）码
	// @gotags: json:"nationcode" bson:"nationcode"
	Nationcode string `protobuf:"bytes,8,opt,name=nationcode,proto3" json:"nationcode" bson:"nationcode"`
	// 开始发起语音通知呼叫时间
	// @gotags: json:"start_calltime" bson:"start_calltime"
	StartCalltime int64 `protobuf:"varint,9,opt,name=start_calltime,json=startCalltime,proto3" json:"start_calltime" bson:"start_calltime"`
}

func (x *Callback) Reset() {
	*x = Callback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_notify_voice_pb_notify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Callback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Callback) ProtoMessage() {}

func (x *Callback) ProtoReflect() protoreflect.Message {
	mi := &file_apps_notify_voice_pb_notify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Callback.ProtoReflect.Descriptor instead.
func (*Callback) Descriptor() ([]byte, []int) {
	return file_apps_notify_voice_pb_notify_proto_rawDescGZIP(), []int{4}
}

func (x *Callback) GetResult() NotifyStatus {
	if x != nil {
		return x.Result
	}
	return NotifyStatus_ABNORMAL
}

func (x *Callback) GetAcceptTime() int64 {
	if x != nil {
		return x.AcceptTime
	}
	return 0
}

func (x *Callback) GetCallFrom() string {
	if x != nil {
		return x.CallFrom
	}
	return ""
}

func (x *Callback) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Callback) GetEndCalltime() int64 {
	if x != nil {
		return x.EndCalltime
	}
	return 0
}

func (x *Callback) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *Callback) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Callback) GetNationcode() string {
	if x != nil {
		return x.Nationcode
	}
	return ""
}

func (x *Callback) GetStartCalltime() int64 {
	if x != nil {
		return x.StartCalltime
	}
	return 0
}

var File_apps_notify_voice_pb_notify_proto protoreflect.FileDescriptor

var file_apps_notify_voice_pb_notify_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x19, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x22, 0x5a,
	0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x37, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xdc, 0x02, 0x0a, 0x06, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x72, 0x69, 0x67, 0x67,
	0x65, 0x72, 0x41, 0x74, 0x12, 0x3f, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78,
	0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x22, 0x3d, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x8b, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xb6, 0x02, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x12, 0x3f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x46, 0x72,
	0x6f, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x65,
	0x6e, 0x64, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x65, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2a,
	0x17, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x54,
	0x45, 0x4e, 0x43, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x2a, 0x34, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x42, 0x4e, 0x4f,
	0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x02, 0x32, 0xbd,
	0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x06, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x12, 0x22, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x74, 0x22, 0x00,
	0x12, 0x5c, 0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x12, 0x23, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x43,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x1a, 0x23, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32,
	0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78,
	0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_notify_voice_pb_notify_proto_rawDescOnce sync.Once
	file_apps_notify_voice_pb_notify_proto_rawDescData = file_apps_notify_voice_pb_notify_proto_rawDesc
)

func file_apps_notify_voice_pb_notify_proto_rawDescGZIP() []byte {
	file_apps_notify_voice_pb_notify_proto_rawDescOnce.Do(func() {
		file_apps_notify_voice_pb_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_notify_voice_pb_notify_proto_rawDescData)
	})
	return file_apps_notify_voice_pb_notify_proto_rawDescData
}

var file_apps_notify_voice_pb_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apps_notify_voice_pb_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_apps_notify_voice_pb_notify_proto_goTypes = []interface{}{
	(Provider)(0),     // 0: infraboard.eventbox.voice.Provider
	(NotifyStatus)(0), // 1: infraboard.eventbox.voice.NotifyStatus
	(*RecordSet)(nil), // 2: infraboard.eventbox.voice.RecordSet
	(*Record)(nil),    // 3: infraboard.eventbox.voice.Record
	(*Response)(nil),  // 4: infraboard.eventbox.voice.Response
	(*Request)(nil),   // 5: infraboard.eventbox.voice.Request
	(*Callback)(nil),  // 6: infraboard.eventbox.voice.Callback
}
var file_apps_notify_voice_pb_notify_proto_depIdxs = []int32{
	3, // 0: infraboard.eventbox.voice.RecordSet.items:type_name -> infraboard.eventbox.voice.Record
	0, // 1: infraboard.eventbox.voice.Record.provider:type_name -> infraboard.eventbox.voice.Provider
	4, // 2: infraboard.eventbox.voice.Record.response:type_name -> infraboard.eventbox.voice.Response
	6, // 3: infraboard.eventbox.voice.Record.callback:type_name -> infraboard.eventbox.voice.Callback
	0, // 4: infraboard.eventbox.voice.Request.provider:type_name -> infraboard.eventbox.voice.Provider
	1, // 5: infraboard.eventbox.voice.Callback.result:type_name -> infraboard.eventbox.voice.NotifyStatus
	5, // 6: infraboard.eventbox.voice.Service.Notify:input_type -> infraboard.eventbox.voice.Request
	6, // 7: infraboard.eventbox.voice.Service.NotifyCallback:input_type -> infraboard.eventbox.voice.Callback
	2, // 8: infraboard.eventbox.voice.Service.Notify:output_type -> infraboard.eventbox.voice.RecordSet
	4, // 9: infraboard.eventbox.voice.Service.NotifyCallback:output_type -> infraboard.eventbox.voice.Response
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_apps_notify_voice_pb_notify_proto_init() }
func file_apps_notify_voice_pb_notify_proto_init() {
	if File_apps_notify_voice_pb_notify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_notify_voice_pb_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_notify_voice_pb_notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_notify_voice_pb_notify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_notify_voice_pb_notify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_notify_voice_pb_notify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Callback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_notify_voice_pb_notify_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_notify_voice_pb_notify_proto_goTypes,
		DependencyIndexes: file_apps_notify_voice_pb_notify_proto_depIdxs,
		EnumInfos:         file_apps_notify_voice_pb_notify_proto_enumTypes,
		MessageInfos:      file_apps_notify_voice_pb_notify_proto_msgTypes,
	}.Build()
	File_apps_notify_voice_pb_notify_proto = out.File
	file_apps_notify_voice_pb_notify_proto_rawDesc = nil
	file_apps_notify_voice_pb_notify_proto_goTypes = nil
	file_apps_notify_voice_pb_notify_proto_depIdxs = nil
}
